### PR TITLE
Require lens >= 5

### LINKED ISSUE #152: Incorrect lower bound for lens
In addition to the broader suggestion in #149 to remove `Safe` pragmas, there's the more immediate problem that p-u doesn't build with lens < 5, but the Cabal file doesn't say so.

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #152.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
In principle, I am supportive of this idea. My only concern about this is that we might make it more difficult to build with other libraries that still require `lens<5`. I don't have a specific example to cite, but I seem to recall that you ran into a situation like this recently?

**Comment by langston-barrett** [comment]
> I don't have a specific example to cite, but I seem to recall that you ran into a situation like this recently?

Yes, unfortunately that's in a closed-source project so I can't share specifics.

> My only concern about this is that we might make it more difficult to build with other libraries that still require lens<5.

Doesn't your example on #149 demonstrate that it's already impossible to build p-u with libraries that depend on lens<5? Or am I misunderstanding that?

FWIW, lens 5 came out a full two years ago.

**Comment by RyanGlScott** [comment]
> Doesn't your example on https://github.com/GaloisInc/parameterized-utils/issues/149 demonstrate that it's already impossible to build p-u with libraries that depend on lens<5?

Currently, that is the case. The question is whether we would want to support doing so into the future. Given how old `lens-5` is, however, perhaps the solution is to just force the rest of the ecosystem to catch up.

**Comment by langston-barrett** [comment]
After merging #151 and so fixing #152, there is no immediate need to change this lower bound.

**Pull request closed without merging**
